name: Generate Rankings

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *" # 毎月1日AM9時 (JST)

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: "2.5.6"

      - name: Execute script
        run: deno task exec
        env:
          CUSTOM_TOKEN: ${{ secrets.CUSTOM_TOKEN }}

      - name: Check for changes
        id: git_diff
        run: |
          git diff --quiet --exit-code docs/ || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        if: steps.git_diff.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/
          git commit -m "docs: update user rankings"
          git push
